---
- name: copy repo list template
  template:
    src: "repo_list.txt"
    dest: "{{ local_working_dir }}/repo_list.txt"
    mode: 0644
  delegate_to: localhost
  become: true
  become_user: root

- name: read repo list
  command: cat {{ local_working_dir }}/repo_list.txt
  delegate_to: localhost
  register: repo_list
  become: true
  become_user: root

- name: copy params template
  template:
    src: "set_params.j2"
    dest: "{{ local_working_dir }}/set_params"
    mode: 0644
  delegate_to: localhost
  become: true
  become_user: root

- name: read parameters
  command: cat {{ local_working_dir }}/set_params
  delegate_to: localhost
  register: params
  become: true
  become_user: root

- name: clear repo tmp files
  file:
    path: "{{ local_working_dir }}/repo_list_tmp.txt"
    state: absent
  delegate_to: localhost
  become: true
  become_user: root

- name: create repo list temp file
  template:
    src: "repo_list.txt"
    dest: "{{ local_working_dir }}/repo_list_tmp.txt"
    mode: 0644
  delegate_to: localhost
  become: true
  become_user: root

- name: clear each repo list file
  file:
    path: "{{ local_working_dir }}/{{ inventory_hostname }}_repo_list.txt"
    state: absent
  delegate_to: localhost
  become: true
  become_user: root

- name: create each repo list file
  file:
    path: "{{ local_working_dir }}/{{ inventory_hostname }}_repo_list.txt"
    state: touch
    mode: 0644
  delegate_to: localhost
  become: true
  become_user: root

- name: copy top amount of repos and add to list
  shell: >
    cat {{ local_working_dir }}/repo_list_tmp.txt | 
    head -{{ params.stdout_lines[groups.all.index(inventory_hostname)] }} 
    >> {{ local_working_dir }}/{{ inventory_hostname }}_repo_list.txt && 
    sed -i '1,{{ params.stdout_lines[groups.all.index(inventory_hostname)] }}d' 
    {{ local_working_dir }}/repo_list_tmp.txt
  args:
    executable: /bin/bash
  delegate_to: localhost
  become: true
  become_user: root

- name: copy delegated repo files
  copy:
    src: "{{ local_working_dir }}/{{ inventory_hostname }}_repo_list.txt"
    dest: "{{ install_dir }}/repo_list"
    mode: 0644
  become: true
  become_user: root

- name: clean up working directory
  file:
    path: "{{ local_working_dir }}/{{ item }}"
    state: absent
  with_items:
    - "{{ inventory_hostname }}_repo_list.txt"
    - "repo_list_tmp.txt"
    - "set_params"
    - "repo_list.txt"
  delegate_to: localhost
  become: true
  become_user: root