---
- name: read repo list
  command: cat /etc/ansible/roles/svn2git/templates/repo_list.txt
  delegate_to: localhost
  register: repo_list

- name: copy params template
  template:
    src: "set_params.j2"
    dest: "/etc/ansible/roles/svn2git/templates/set_params"
    mode: 0644
  delegate_to: localhost
  become: true
  become_user: root

- name: read parameters
  command: cat /etc/ansible/roles/svn2git/templates/set_params
  delegate_to: localhost
  register: params

- name: clear repo tmp file
  file:
    path: /etc/ansible/roles/svn2git/templates/repo_list_tmp.txt
    state: absent
  delegate_to: localhost
  become: true
  become_user: root

- name: copy repo_list file
  copy:
    src: "/etc/ansible/roles/svn2git/templates/repo_list.txt"
    dest: "/etc/ansible/roles/svn2git/templates/repo_list_tmp.txt"
    mode: 0777
    remote_src: true
  delegate_to: localhost
  become: true
  become_user: root

- name: clear each repo list file
  file:
    path: /etc/ansible/roles/svn2git/templates/{{ inventory_hostname }}_repo_list.txt
    state: absent
  delegate_to: localhost
  become: true
  become_user: root

- name: create each repo list file
  file:
    path: /etc/ansible/roles/svn2git/templates/{{ inventory_hostname }}_repo_list.txt
    state: touch
    mode: 0644
  delegate_to: localhost
  become: true
  become_user: root

- name: copy top amount of repos and add to list
  shell: >
    cat /etc/ansible/roles/svn2git/templates/repo_list_tmp.txt | 
    head -{{ params.stdout_lines[groups.all.index(inventory_hostname)] }} 
    >> /etc/ansible/roles/svn2git/templates/{{ inventory_hostname }}_repo_list.txt && 
    sed -i '1,{{ params.stdout_lines[groups.all.index(inventory_hostname)] }}d' 
    /etc/ansible/roles/svn2git/templates/repo_list_tmp.txt
  args:
    executable: /bin/bash
  delegate_to: localhost
  become: true
  become_user: root

- name: copy delegated repo templates
  template:
    src: "{{ inventory_hostname }}_repo_list.txt"
    dest: "/opt/svn2git/repo_list"
    mode: 0644
  become: true
  become_user: root

- name: clean up each repo list file
  file:
    path: /etc/ansible/roles/svn2git/templates/{{ inventory_hostname }}_repo_list.txt
    state: absent
  delegate_to: localhost
  become: true
  become_user: root

- name: clean up repo tmp file
  file:
    path: /etc/ansible/roles/svn2git/templates/repo_list_tmp.txt
    state: absent
  delegate_to: localhost
  become: true
  become_user: root

- name: clean up set_params file
  file:
    path: /etc/ansible/roles/svn2git/templates/set_params
    state: absent
  delegate_to: localhost
  become: true
  become_user: root