---
#tasks file for svn2git
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "git-all"
    - "subversion"
    - "perl"
  become: true
  become_user: root

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ install_dir }}"
    - "{{ install_dir }}/repos"
    - "{{ install_dir }}/logs"
  become: true
  become_user: root

- name: copy authors list
  template:
    src: "authors.txt"
    dest: "{{ install_dir }}/repos/authors"
    mode: 0766
  become: true
  become_user: root

# this block creates the webpage for displaying conversion status
########################
- block:
  - name: install apache and php
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "php"
      - "httpd"

  - name: start apache
    service:
      name: httpd
      state: started
      enabled: yes
  
  - name: create count files
    shell: echo "{{ item.input }}" > {{ item.name }}
    args:
      chdir: /var/www/html
    with_items:
      - { name: "countlog.txt", input: "0" }
      - { name: "success_countlog.txt", input: "0" }
      - { name: "failed_countlog.txt", input: "0" }
      - { name: "push_queue.txt", input: "" }

  - name: change permissions of count files
    file:
      path: "/var/www/html/{{ item }}"
      state: touch
      mode: 0764
      owner: apache
      group: apache
    with_items:
      - "countlog.txt"
      - "success_countlog.txt"
      - "failed_countlog.txt"
      - "push_queue.txt"

  - name: copy repo list
    template:
      src: "repo_list.txt"
      dest: "/var/www/html/repo_list"
      mode: 0764
      owner: apache
      group: apache

  - name: read repo list
    command: cat /var/www/html/repo_list
    register: repo_list

  - name: set total_repos variable
    set_fact:
      total_repos: "{{ repo_list.stdout_lines|length }}"

  - name: copy webpage templates
    template:
      src: "{{ item.src }}"
      dest: "/var/www/html/{{ item.dest }}"
      mode: 0764
      owner: apache
      group: apache
    with_items:
      - { src: "index.php.j2", dest: "index.php" }
      - { src: "table.html.j2", dest: "table.html" }
      - { src: "queue_table.html.j2", dest: "queue_table.html" }
      - { src: "repo_list.txt", dest: "repo_list" }

  - name: allow connections to httpd
    shell: "{{ item }}"
    with_items:
      - "setsebool -P httpd_unified 1"
      - "setsebool -P httpd_can_network_connect 1"
    when: ansible_distribution == "CentOS"

  - name: restart apache
    service:
      name: httpd
      state: restarted
      enabled: yes
  become: true
  become_user: root
  when: "inventory_hostname == groups.all[0]"
###############################

- name: copy bash script
  template:
    src: "gitMigration.sh.j2"
    dest: "{{ install_dir }}/repos/gitMigration.sh"
    mode: 0755
  become: true
  become_user: root

- name: execute bash scripts
  shell: nohup ./gitMigration.sh &
  args:
    chdir: "{{ install_dir }}/repos"
  become: true
  become_user: root

- name: show webpage address
  debug:
    msg: "Go to http://{{ groups.all[0] }} for the conversion status page."
  when: "inventory_hostname == groups.all[0]"