---
#tasks file for svn2git
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "git-all"
    - "subversion"
    - "perl"
  become: true
  become_user: root

- name: create directory
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: 0755
  become: true
  become_user: root

- name: create remote working directory
  file:
    path: "{{ remote_working_dir }}"
    state: directory
    mode: 0755
  become: true
  become_user: root
  when: "inventory_hostname == groups.all[0]"

- name: include list creation
  include: create_lists.yml
  become: true
  become_user: root

# lists are created and placed on servers