---
#tasks file for svn2git
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "git-all"
    - "subversion"
    - "perl"
  become: true
  become_user: root

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ install_dir }}"
    - "{{ install_dir }}/repos"
    - "{{ install_dir }}/logs"
  become: true
  become_user: root

- name: create remote working directory
  file:
    path: "{{ remote_working_dir }}"
    state: directory
    mode: 0755
  become: true
  become_user: root
  when: "inventory_hostname == groups.all[0]"

- name: include list creation
  include: create_lists.yml
  become: true
  become_user: root

- name: copy bash script
  template:
    src: "gitMigration.sh.j2"
    dest: "{{ install_dir }}/repos/gitMigration.sh"
    mode: 0755
  become: true
  become_user: root

- name: execute bash scripts
  shell: nohup ./gitMigration.sh & 
  args:
    chdir: "{{ install_dir }}/repos"